[global]
    workgroup = WORKGROUP
    server string = KiTS CS CTF Printer Shares
    security = user
    map to guest = Bad User
    guest account = nobody
    server min protocol = SMB2
    smb ports = 445
    log level = 0

[shares]
    path = /srv/shares
    browseable = yes
    read only = no
    writable = yes
    guest ok = yes
    force user = nobody
    create mask = 0666
    force create mode = 0666
    directory mask = 0777
    force directory mode = 0777

[secure-shares]
    path = /challenge/secure-shares
    browseable = no
    read only = yes
    guest ok = no
    valid users = admin
